version: 2

sources:
  - name: staging
    database: dbt
    schema: dbt_dev

    tables: 
      - name: customer
      - name: orders
      - name: state


models:
    - name: stg_customer
      columns:
          - name: customer_id
            tests:
                - not_null

    - name: stg_orders
      columns:
          - name: order_id
            tests:
                - unique
                - not_null
    
    - name: stg_state
      columns:
          - name: state_code
            tests:
                - accepted_values:
                    values:
                        [
                          "AC",
                          "AL",
                          "AP",
                          "AM",
                          "BA",
                          "CE",
                          "DF",
                          "ES",
                          "GO",
                          "MA",
                          "MT",
                          "MS",
                          "MG",
                          "PA",
                          "PB",
                          "PR",
                          "PE",
                          "PI",
                          "RJ",
                          "RN",
                          "RS",
                          "RO",
                          "RR",
                          "SC",
                          "SP",
                          "SE",
                         "TO"
                        ]