version: 2

models:
    - name: customer_orders
      columns:
          - name: customer_id
            description: Unique id for a customer
            tests:
               - not_null
          - name: order_status
            description: 1 if order is delivered, 0 otherwise
            tests:
               - accepted_values:
                   values: [1,0]
          - name: state_name
            description: The full state name of