name: 'simple_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'simple_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt-modules"


models:
  simple_dbt_project:
    materialized: table

    staging:
        materialized: view
