simple_dbt_project:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: dbt
      pass: password1234
      dbname: dbt
      schema: dbt_dev

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: dbt
      pass: password1234
      dbname: dbt
      schema: dbt_prod
  target: dev
